# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThreeRocksDrawn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Parse'
  pod 'SCLAlertView'
  pod 'TextFieldEffects'
  pod 'CameraManager', '~> 5.1'
  # Pods for ThreeRocksDrawn

  target 'ThreeRocksDrawnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThreeRocksDrawnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
